# Generated by Django 6.0.5 on 2026-06-03 06:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("landlord", "Landlord")],
                        default="student",
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_top_rated", models.BooleanField(default=False)),
                ("is_quick_responder", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="LandlordProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("national_id", models.CharField(blank=True, max_length=50, null=True)),
                ("is_id_verified", models.BooleanField(default=False)),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landlord_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("university", models.CharField(blank=True, max_length=255, null=True)),
                ("faculty", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "year_of_study",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("languages", models.JSONField(blank=True, default=list)),
                ("profile_strength", models.IntegerField(default=0)),
                ("is_looking_for_room", models.BooleanField(default=False)),
                ("lifestyle_tags", models.JSONField(blank=True, default=list)),
                (
                    "sleeping_time",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("early", "Early (9-10 PM)"),
                            ("normal", "Normal (11 PM)"),
                            ("late", "Late (12+ AM)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "study_environment",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "music_preference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "guests_policy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("never", "Never"),
                            ("sometimes", "Sometimes"),
                            ("often", "Often"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "personality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quiet", "Quiet"),
                            ("social", "Social"),
                            ("moderate", "Moderate"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cleanliness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "smoking",
                    models.CharField(
                        blank=True,
                        choices=[("smoker", "Smoker"), ("non_smoker", "Non-Smoker")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("budget_min", models.IntegerField(default=0)),
                ("budget_max", models.IntegerField(default=0)),
                (
                    "room_type_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("shared", "Shared"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "preferred_room_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("shared", "Shared"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "smoking_preference",
                    models.CharField(
                        blank=True,
                        choices=[("smoker", "Smoker"), ("non_smoker", "Non-Smoker")],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "sleep_schedule_pref",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("early", "Early (9-10 PM)"),
                            ("normal", "Normal (11 PM)"),
                            ("late", "Late (12+ AM)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cleanliness_pref",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "personality_pref",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quiet", "Quiet"),
                            ("social", "Social"),
                            ("moderate", "Moderate"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("student_id", "Student ID"),
                            ("university_email", "University Email"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="verifications/"),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
