# Generated by Django 6.0.5 on 2026-06-03 06:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("studio", "Studio"),
                            ("room", "Room"),
                            ("shared", "Shared Room"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "nearby_university",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "distance_to_university",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "transport_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("walk", "Walking"),
                            ("metro", "Metro"),
                            ("transport", "Public Transport"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("num_rooms", models.IntegerField(default=1)),
                ("num_beds", models.IntegerField(default=1)),
                ("num_bathrooms", models.IntegerField(default=1)),
                ("num_roommates", models.IntegerField(default=0)),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("area_sqm", models.IntegerField(blank=True, null=True)),
                (
                    "gender_preference",
                    models.CharField(
                        choices=[("male", "Males Only"), ("female", "Females Only")],
                        max_length=10,
                    ),
                ),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("min_stay_months", models.IntegerField(default=1)),
                ("max_stay_months", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("rented", "Rented"),
                            ("unavailable", "Unavailable"),
                            ("reserved", "Reserved"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landlord_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images/")),
                ("is_cover", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_cover", "uploaded_at"],
            },
        ),
    ]
