# Generated by Django 6.0.5 on 2026-06-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NearbyPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("query_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("supermarket", "Supermarket"),
                            ("pharmacy", "Pharmacy"),
                            ("restaurant", "Restaurant"),
                            ("cafe", "Café"),
                            ("gym", "Gym"),
                            ("hospital", "Hospital"),
                            ("bank", "Bank"),
                            ("atm", "ATM"),
                            ("bus_station", "Bus Station"),
                            ("metro_station", "Metro Station"),
                            ("mosque", "Mosque"),
                            ("library", "Library"),
                            ("laundry", "Laundry"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("radius_m", models.PositiveIntegerField(default=1500)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("distance_m", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("open_now", models.BooleanField(blank=True, null=True)),
                ("cached_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["distance_m"],
                "indexes": [
                    models.Index(
                        fields=["query_lat", "query_lng", "place_type"],
                        name="services_ne_query_l_e0b6a8_idx",
                    )
                ],
            },
        ),
    ]
