# Generated by Django 6.0.5 on 2026-06-03 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoommateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("bio", models.TextField(blank=True, null=True)),
                ("university", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("move_in_date", models.DateField(blank=True, null=True)),
                ("budget_min", models.IntegerField(default=0)),
                ("budget_max", models.IntegerField(default=0)),
                (
                    "sleeping_time",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("early", "Early (9–10 PM)"),
                            ("normal", "Normal (11 PM)"),
                            ("late", "Late (12+ AM)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cleanliness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "personality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quiet", "Quiet"),
                            ("social", "Social"),
                            ("moderate", "Moderate"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "smoking",
                    models.CharField(
                        blank=True,
                        choices=[("smoker", "Smoker"), ("non_smoker", "Non-Smoker")],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "guests_policy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("never", "Never"),
                            ("sometimes", "Sometimes"),
                            ("often", "Often"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "room_type_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("shared", "Shared"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "smoking_preference",
                    models.CharField(
                        blank=True,
                        choices=[("smoker", "Smoker"), ("non_smoker", "Non-Smoker")],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "sleep_schedule_pref",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("early", "Early (9–10 PM)"),
                            ("normal", "Normal (11 PM)"),
                            ("late", "Late (12+ AM)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cleanliness_pref",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "personality_pref",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quiet", "Quiet"),
                            ("social", "Social"),
                            ("moderate", "Moderate"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoommateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_roommate_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_roommate_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("sender", "receiver")},
            },
        ),
    ]
