# Generated by Django 6.0.5 on 2026-05-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={},
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payment_token",
            new_name="failure_reason",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="is_success",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="landlord",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paymob_transaction_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="student",
        ),
        migrations.AddField(
            model_name="payment",
            name="amount_cents",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("online", "Online (Paymob)"), ("offline", "Offline (Cash)")],
                default="online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("remaining", "Remaining")],
                default="deposit",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="raw_response",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="WithdrawalRequest",
        ),
    ]
