# Generated by Django 6.0.5 on 2026-05-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_deposit_amount_cents_booking_expires_at_and_more"),
        ("payments", "0002_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "completed")),
                fields=("booking", "payment_type"),
                name="unique_completed_payment_type_per_booking",
            ),
        ),
    ]
